# Generated by Django 5.2.3 on 2025-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('producers', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('planets', models.ManyToManyField(related_name='movies', to='planets.planet')),
            ],
        ),
    ]
