# Generated by Django 5.2.3 on 2025-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('climate', models.CharField(blank=True, max_length=100, null=True)),
                ('terrain', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
